logger:
  level: INFO

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

time:
  - platform: homeassistant
    id: ha_time

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "Panel IP Address"
    ssid:
      name: "Panel Wi-Fi SSID"

sensor:
  - platform: uptime
    name: "Panel Uptime"
  - platform: wifi_signal
    name: "Panel Wi-Fi RSSI"
    id: panel_wifi_rssi
    update_interval: 30s

binary_sensor:
  - platform: status
    name: "Panel Online"
